version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /dans-blog/node_modules
      - .:/dans-blog
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
