name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: node:10.17.0-alpine
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}